[[redirects]]
  from = "/cardapio-bar-piscina.php"
  to = "/cardapio-bar-piscina.html"

[[redirects]]
  from = "/*"
  to = "/manutencao.html"

[[redirects]]
  from = "/index.html"
  to = "/manutencao.html"

[[redirects]]
  from = "/quem-somos.html"
  to = "/manutencao.html"

[[redirects]]
  from = "/cardapio-bar-piscina.html"
  to = "/manutencao.html"

[[redirects]]
  from = "/contato.html"
  to = "/manutencao.html"