backend:
  name: git-gateway
  branch: main

media_folder: "src/img"
  
collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - label: "Cardápio Bar da Piscina"
        name: "cardapio-bar-piscina"
        file: "src/cardapio-bar-piscina.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Corpo", name: "body", widget: "markdown" }