backend:
  name: git-gateway
  branch: main

media_folder: "src/img"
  
collections:
  - name: "paginas"
    label: "Páginas"
    folder: "src"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }